### ISSUE TITLE
Can unipop support multi mappings for different graph models running at the same time?

### ISSUE THREAD

**Issue by sorryya** [unipop-graph/unipop#117]
Can unipop support multi mappings for different graph models running at the same time?
If yes, how should I configure?
If no, will you plan to support it?

**Comment by seanbarzilay** [comment]
Do you mean something like this:
```java
UniGraph graph1 = UniGraph.open(conf1);
UniGraph graph2 = UniGraph.open(conf2);
```

**Comment by baozengkai** [comment]
@seanbarzilay This is unipop-console and JVM way, But unipop-server how to configure?

**Comment by seanbarzilay** [comment]
You can simply add 
```yaml
graphs: {
    graph: path/to/properties/file,
    graph2: path/to/properties/file2
}
```
to your gremlin-server.yaml file.
